// Generated by tools/make_fonts.py
#pragma once
#include <lvgl.h>
LV_FONT_DECLARE(barlow_cond_bold_84)
LV_FONT_DECLARE(barlow_cond_bold_40)
LV_FONT_DECLARE(barlow_cond_bold_22)
LV_FONT_DECLARE(barlow_cond_semibold_16)
LV_FONT_DECLARE(barlow_cond_semibold_12)
