/* Generated by tools/make_logos.py */
#pragma once
#include <lvgl.h>
#include <string.h>
#include <stdint.h>
#ifdef __cplusplus
extern "C" {
#endif
#define KB_TEAM_COUNT 30
#define KB_LOGO_SIZE 56
typedef struct { const char* abbr; const char* name; uint32_t color; uint32_t alt_color; const lv_image_dsc_t* logo; } kb_team_t;
extern const kb_team_t kb_teams[KB_TEAM_COUNT];
const kb_team_t* kb_find_team(const char* abbr);
extern const lv_image_dsc_t logo_atl;
extern const lv_image_dsc_t logo_bkn;
extern const lv_image_dsc_t logo_bos;
extern const lv_image_dsc_t logo_cha;
extern const lv_image_dsc_t logo_chi;
extern const lv_image_dsc_t logo_cle;
extern const lv_image_dsc_t logo_dal;
extern const lv_image_dsc_t logo_den;
extern const lv_image_dsc_t logo_det;
extern const lv_image_dsc_t logo_gs;
extern const lv_image_dsc_t logo_hou;
extern const lv_image_dsc_t logo_ind;
extern const lv_image_dsc_t logo_lac;
extern const lv_image_dsc_t logo_lal;
extern const lv_image_dsc_t logo_mem;
extern const lv_image_dsc_t logo_mia;
extern const lv_image_dsc_t logo_mil;
extern const lv_image_dsc_t logo_min;
extern const lv_image_dsc_t logo_no;
extern const lv_image_dsc_t logo_ny;
extern const lv_image_dsc_t logo_okc;
extern const lv_image_dsc_t logo_orl;
extern const lv_image_dsc_t logo_phi;
extern const lv_image_dsc_t logo_phx;
extern const lv_image_dsc_t logo_por;
extern const lv_image_dsc_t logo_sa;
extern const lv_image_dsc_t logo_sac;
extern const lv_image_dsc_t logo_tor;
extern const lv_image_dsc_t logo_utah;
extern const lv_image_dsc_t logo_wsh;
#ifdef __cplusplus
}
#endif
