// Generated by tools/train_winprob.py; do not edit.
// Trained on the 2024-25 season, held out 2025-26: Brier 0.1617 (ESPN 0.1474), log loss 0.4764 (ESPN 0.4418).
#pragma once
#define WINPROB_A     -0.0137034f
#define WINPROB_B_MS  0.0956410f
#define WINPROB_B_S   0.1843728f
#define WINPROB_B_M   -0.0110559f
#define WINPROB_EPS   0.0050000f
#define WINPROB_TRAIN_CELLS 35221
#define WINPROB_TRAIN_PLAYS 623853
