// Generated by tools/train_winprob.py; do not edit.
// Trained on the 2024-25 season, held out 2025-26: Brier 0.1617 (ESPN 0.1474), log loss 0.4764 (ESPN 0.4418).
#pragma once
#define WINPROB_A     -0.0137265f
#define WINPROB_B_MS  0.0956615f
#define WINPROB_B_S   0.1843979f
#define WINPROB_B_M   -0.0110844f
#define WINPROB_EPS   0.0050000f
