#!/usr/bin/env python3
"""Sanity-check the captured ESPN fixtures with the reference (Python) parser.

The firmware's C++ parser is tested by `pio test -e native`; this checks the same fixtures
with the Python mirror in espn_probe.py so a fixture regenerated by make_fixtures.py can't
silently drift from what the tests assume. Exit code 1 on any mismatch.
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from espn_probe import parse  # noqa: E402

FIXTURES = Path(__file__).resolve().parent.parent / "firmware" / "test" / "fixtures"

EXPECT = {
    "pre": {"state": "pre", "us_home": True, "them": "LAL", "score": None},
    "live": {"state": "in", "period": 4, "clock": "2:31", "them": "GS"},
    "post_win": {"state": "post", "completed": True, "us_winner": True, "them": "GS"},
    "post_loss": {"state": "post", "completed": True, "us_winner": False, "them": "LAC"},
}


def main():
    bad = 0
    for name, exp in EXPECT.items():
        path = FIXTURES / f"{name}.json"
        if not path.exists():
            print(f"MISSING {path}")
            bad += 1
            continue
        p = parse(json.loads(path.read_text()), "sac")
        us = next(t for t in p["teams"] if t["is_us"])
        them = next(t for t in p["teams"] if not t["is_us"])
        got = {
            "state": p["state"], "completed": p.get("completed"), "period": p.get("period"), "clock": p.get("clock"),
            "them": them["abbr"], "us_home": us["home_away"] == "home", "score": us["score"], "us_winner": us.get("winner"),
        }
        errs = [f"{k}: expected {v!r}, got {got[k]!r}" for k, v in exp.items() if got[k] != v]
        status = "ok " if not errs else "BAD"
        print(f"{status} {name:10s} {p['state']:4s} {us['abbr']} {us['score']} - {them['abbr']} {them['score']}" + ("  " + "; ".join(errs) if errs else ""))
        bad += bool(errs)
    sys.exit(1 if bad else 0)


if __name__ == "__main__":
    main()
