#!/usr/bin/env python3
"""Convert TTF fonts to LVGL 9 "fmt_txt" C fonts (4 bpp, uncompressed), no node/lv_font_conv needed.

Output goes to firmware/src/fonts/<name>.c. The format matches lvgl 9.2.x:
  - glyph bitmaps: 4 bpp, 2 px/byte high nibble first, pixels packed continuously across rows
    (no row padding), each glyph padded to a byte boundary
  - lv_font_fmt_txt_glyph_dsc_t: bitmap_index, adv_w (8.4 fixed), box_w, box_h, ofs_x, ofs_y
    where ofs_y is the glyph bottom relative to the baseline (negative for descenders)
  - one FORMAT0_TINY cmap for the contiguous ASCII range 0x20..0x7E, plus a sparse cmap for
    the middle dot and en dash used in the UI

Usage: python3 tools/make_fonts.py
"""
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parent.parent
FONT_DIR = ROOT / "tools" / "fonts"
OUT_DIR = ROOT / "firmware" / "src" / "fonts"

# (c name, ttf file, pixel size, character set)
DIGITS_PUNCT = "0123456789:-–· "
ASCII = "".join(chr(c) for c in range(0x20, 0x7F))
EXTRA = "·–"   # U+00B7 middle dot, U+2013 en dash
FONTS = [
    ("barlow_cond_bold_84",     "BarlowCondensed-Bold.ttf",     84, DIGITS_PUNCT),
    ("barlow_cond_bold_40",     "BarlowCondensed-Bold.ttf",     40, ASCII + EXTRA),
    ("barlow_cond_bold_22",     "BarlowCondensed-Bold.ttf",     22, ASCII + EXTRA),
    ("barlow_cond_semibold_16", "BarlowCondensed-SemiBold.ttf", 16, ASCII + EXTRA),
    ("barlow_cond_semibold_12", "BarlowCondensed-SemiBold.ttf", 12, ASCII + EXTRA),
]


def render_glyph(font: ImageFont.FreeTypeFont, ch: str):
    """Return (bitmap rows as list of lists of 0-15, box_w, box_h, ofs_x, ofs_y, adv_w_px)."""
    adv = font.getlength(ch)
    # bbox relative to the baseline-left anchor: (x0, y0, x1, y1), y grows downward
    x0, y0, x1, y1 = font.getbbox(ch, anchor="ls")
    w, h = x1 - x0, y1 - y0
    if w <= 0 or h <= 0:
        return [], 0, 0, 0, 0, adv
    # render with 4x supersampling for cleaner antialiasing at small sizes
    img = Image.new("L", (w, h), 0)
    d = ImageDraw.Draw(img)
    d.text((-x0, -y0), ch, font=font, fill=255, anchor="ls")
    px = img.load()
    rows = [[(px[x, y] + 8) // 17 for x in range(w)] for y in range(h)]
    rows = [[min(15, v) for v in r] for r in rows]
    # trim fully-empty edge rows/cols so box is tight
    while rows and all(v == 0 for v in rows[0]):
        rows.pop(0); y0 += 1
    while rows and all(v == 0 for v in rows[-1]):
        rows.pop(); y1 -= 1
    if not rows:
        return [], 0, 0, 0, 0, adv
    cols = list(zip(*rows))
    left = 0
    while left < len(cols) and all(v == 0 for v in cols[left]):
        left += 1
    right = len(cols)
    while right > left and all(v == 0 for v in cols[right - 1]):
        right -= 1
    rows = [r[left:right] for r in rows]
    box_w, box_h = right - left, len(rows)
    ofs_x = x0 + left
    ofs_y = -y1          # bottom of box relative to baseline; y1 > 0 means below baseline
    return rows, box_w, box_h, ofs_x, ofs_y, adv


def pack4(rows):
    out = bytearray()
    nib = []
    for r in rows:
        for v in r:
            nib.append(v)
    for i in range(0, len(nib), 2):
        hi = nib[i]
        lo = nib[i + 1] if i + 1 < len(nib) else 0
        out.append((hi << 4) | lo)
    return bytes(out)


def build(name, ttf, size, charset):
    font = ImageFont.truetype(str(FONT_DIR / ttf), size)
    ascent, descent = font.getmetrics()
    line_height = ascent + descent
    base_line = descent

    chars = sorted(set(charset), key=ord)
    bitmap = bytearray()
    glyphs = []   # (bitmap_index, adv_w16, box_w, box_h, ofs_x, ofs_y, ch)
    glyphs.append((0, 0, 0, 0, 0, 0, None))   # glyph id 0 = reserved/undefined
    for ch in chars:
        rows, bw, bh, ox, oy, adv = render_glyph(font, ch)
        idx = len(bitmap)
        bitmap += pack4(rows)
        glyphs.append((idx, int(round(adv * 16)), bw, bh, ox, oy, ch))

    # cmaps: split into contiguous runs
    runs = []
    for gid, g in enumerate(glyphs):
        if g[6] is None:
            continue
        cp = ord(g[6])
        if runs and runs[-1][1] + runs[-1][2] == cp and runs[-1][3] + runs[-1][2] == gid:
            runs[-1][2] += 1
        else:
            runs.append([cp, cp, 1, gid])   # [start, start, length, glyph_id_start]

    lines = []
    L = lines.append
    L(f"/* Generated by tools/make_fonts.py from {ttf} at {size} px. Do not edit. */")
    L('#ifdef LV_LVGL_H_INCLUDE_SIMPLE\n#include "lvgl.h"\n#else\n#include "lvgl/lvgl.h"\n#endif')
    L(f"#ifndef {name.upper()}\n#define {name.upper()} 1\n#endif\n#if {name.upper()}\n")
    L("static const uint8_t glyph_bitmap[] = {")
    for i in range(0, len(bitmap), 16):
        L("    " + ", ".join(f"0x{b:02x}" for b in bitmap[i:i + 16]) + ",")
    L("};\n")
    L("static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {")
    for (idx, adv, bw, bh, ox, oy, ch) in glyphs:
        safe = "?" if ch in ("\\", "*", "/") else ch
        cmt = f" /* U+{ord(ch):04X} '{safe}' */" if ch else " /* id 0 reserved */"
        L(f"    {{.bitmap_index = {idx}, .adv_w = {adv}, .box_w = {bw}, .box_h = {bh}, .ofs_x = {ox}, .ofs_y = {oy}}},{cmt}")
    L("};\n")
    L("static const lv_font_fmt_txt_cmap_t cmaps[] = {")
    for (start, _, length, gid) in runs:
        L(f"    {{.range_start = {start}, .range_length = {length}, .glyph_id_start = {gid}, "
          f".unicode_list = NULL, .glyph_id_ofs_list = NULL, .list_length = 0, .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY}},")
    L("};\n")
    L("static const lv_font_fmt_txt_dsc_t font_dsc = {")
    L("    .glyph_bitmap = glyph_bitmap, .glyph_dsc = glyph_dsc, .cmaps = cmaps, .kern_dsc = NULL,")
    L(f"    .kern_scale = 0, .cmap_num = {len(runs)}, .bpp = 4, .kern_classes = 0, .bitmap_format = 0,")
    L("};\n")
    L(f"const lv_font_t {name} = {{")
    L("    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,")
    L("    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,")
    L(f"    .line_height = {line_height}, .base_line = {base_line},")
    L("    .subpx = LV_FONT_SUBPX_NONE, .underline_position = -2, .underline_thickness = 1,")
    L("    .dsc = &font_dsc, .fallback = NULL, .user_data = NULL")
    L("};\n")
    L(f"#endif /* {name.upper()} */")

    out = OUT_DIR / f"{name}.c"
    out.write_text("\n".join(lines) + "\n")
    print(f"{out.name}: {len(chars)} glyphs, {len(bitmap):,} B bitmap, line_height {line_height}, base_line {base_line}")


def main():
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for f in FONTS:
        build(*f)
    (OUT_DIR / "fonts.h").write_text(
        "// Generated by tools/make_fonts.py\n#pragma once\n#include <lvgl.h>\n"
        + "".join(f"LV_FONT_DECLARE({n})\n" for n, *_ in FONTS))


if __name__ == "__main__":
    main()
