#!/usr/bin/env python3
"""Download the 30 NBA team logos from ESPN and emit them as LVGL 9 RGB565A8 images plus a
team table (abbreviation, name, primary color) for the firmware.

Outputs:
  firmware/src/logos.c   image data + lv_image_dsc_t per team + kb_teams[] table
  firmware/src/logos.h   declarations

Usage: python3 tools/make_logos.py [--size 56]
"""
import argparse
import json
import struct
import urllib.request
from io import BytesIO
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "tools" / "logos_src"
OUT = ROOT / "firmware" / "src"
TEAMS_URL = "https://site.api.espn.com/apis/site/v2/sports/basketball/nba/teams?limit=50"
LOGO_URL = "https://a.espncdn.com/i/teamlogos/nba/500/{abbr}.png"
UA = "ESP32HTTPClient"
LV_IMAGE_HEADER_MAGIC = 0x19
LV_COLOR_FORMAT_RGB565A8 = 0x14


OFFLINE = False


def get(url: str) -> bytes:
    if OFFLINE:
        raise SystemExit(f"--offline: would need to download {url}")
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as r:
        return r.read()


def load_teams():
    p = SRC / "teams.json"
    if not p.exists():
        p.write_bytes(get(TEAMS_URL))
    doc = json.loads(p.read_text())
    teams = []
    for t in doc["sports"][0]["leagues"][0]["teams"]:
        t = t["team"]
        teams.append({
            "abbr": t["abbreviation"],
            "name": t["shortDisplayName"],
            "color": t.get("color") or "888888",
            "alt": t.get("alternateColor") or "ffffff",
        })
    return sorted(teams, key=lambda x: x["abbr"])


def logo_png(abbr: str) -> Image.Image:
    p = SRC / f"{abbr.lower()}.png"
    if not p.exists():
        p.write_bytes(get(LOGO_URL.format(abbr=abbr.lower())))
    return Image.open(p).convert("RGBA")


def to_rgb565a8(img: Image.Image, size: int):
    img = img.copy()
    img.thumbnail((size, size), Image.LANCZOS)
    canvas = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    canvas.paste(img, ((size - img.width) // 2, (size - img.height) // 2), img)
    # premultiply against black so edge halos don't show on the dark background
    px = canvas.load()
    rgb = bytearray()
    alpha = bytearray()
    for y in range(size):
        for x in range(size):
            r, g, b, a = px[x, y]
            v = ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)
            rgb += struct.pack("<H", v)   # little-endian, LVGL native RGB565
            alpha.append(a)
    return bytes(rgb) + bytes(alpha)


def c_array(data: bytes, per_line=24):
    lines = []
    for i in range(0, len(data), per_line):
        lines.append("    " + ",".join(f"0x{b:02x}" for b in data[i:i + per_line]) + ",")
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--size", type=int, default=56)
    ap.add_argument("--offline", action="store_true", help="never touch the network; fail if a cached file is missing")
    args = ap.parse_args()
    global OFFLINE
    OFFLINE = args.offline
    size = args.size

    teams = load_teams()
    c = []
    h = []
    c.append("/* Generated by tools/make_logos.py. Team logos are ESPN/NBA property, embedded for personal use. */")
    c.append('#include "logos.h"\n')
    for t in teams:
        data = to_rgb565a8(logo_png(t["abbr"]), size)
        var = f"logo_{t['abbr'].lower()}"
        c.append(f"static const uint8_t {var}_map[] LV_ATTRIBUTE_MEM_ALIGN = {{\n{c_array(data)}\n}};")
        c.append(f"const lv_image_dsc_t {var} = {{")
        c.append(f"    .header = {{.magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_RGB565A8, .flags = 0, "
                 f".w = {size}, .h = {size}, .stride = {size * 2}, .reserved_2 = 0}},")
        c.append(f"    .data_size = sizeof({var}_map), .data = {var}_map, .reserved = NULL,")
        c.append("};\n")
        print(f"{t['abbr']:4s} {t['name']:14s} #{t['color']}  {len(data):,} B")

    c.append("const kb_team_t kb_teams[KB_TEAM_COUNT] = {")
    for t in teams:
        c.append(f'    {{"{t["abbr"]}", "{t["name"]}", 0x{t["color"]}, 0x{t["alt"]}, &logo_{t["abbr"].lower()}}},')
    c.append("};\n")
    c.append("const kb_team_t* kb_find_team(const char* abbr) {")
    c.append("    for (int i = 0; i < KB_TEAM_COUNT; i++) if (strcasecmp(kb_teams[i].abbr, abbr) == 0) return &kb_teams[i];")
    c.append("    return NULL;\n}")

    h.append("/* Generated by tools/make_logos.py */")
    h.append("#pragma once\n#include <lvgl.h>\n#include <string.h>\n#include <stdint.h>")
    h.append("#ifdef __cplusplus\nextern \"C\" {\n#endif")
    h.append(f"#define KB_TEAM_COUNT {len(teams)}\n#define KB_LOGO_SIZE {size}")
    h.append("typedef struct { const char* abbr; const char* name; uint32_t color; uint32_t alt_color; const lv_image_dsc_t* logo; } kb_team_t;")
    h.append("extern const kb_team_t kb_teams[KB_TEAM_COUNT];")
    h.append("const kb_team_t* kb_find_team(const char* abbr);")
    for t in teams:
        h.append(f"extern const lv_image_dsc_t logo_{t['abbr'].lower()};")
    h.append("#ifdef __cplusplus\n}\n#endif")

    (OUT / "logos.c").write_text("\n".join(c) + "\n")
    (OUT / "logos.h").write_text("\n".join(h) + "\n")
    total = len(teams) * size * size * 3
    print(f"\nwrote firmware/src/logos.c ({total:,} B of image data) and logos.h")


if __name__ == "__main__":
    main()
